from .model_catalog_data import (
    models_structure,
    HIDREAM_INFO_LINK,
    GGUF_QUALITY_INFO,
    # Import all the individual entry definitions
    ltx_vae_companion_entry,
    wan_causvid_14b_lora_v2_entry,
    wan_causvid_14b_lora_entry,
    wan_causvid_1_3b_lora_entry,
    wan_self_forcing_lora_entry,
    wan_lightx2v_lora_entry,
    wan_uni3c_controlnet_lora_entry,
    wan_vae_entry,
    wan_fusionx_i2v_gguf_q4_entry,
    wan_fusionx_i2v_gguf_q5_entry,
    wan_fusionx_i2v_gguf_q6_entry,
    wan_fusionx_i2v_gguf_q8_entry,
    wan_fusionx_t2v_gguf_q4_entry,
    wan_fusionx_t2v_gguf_q5_entry,
    wan_fusionx_t2v_gguf_q6_entry,
    wan_fusionx_t2v_gguf_q8_entry,
    wan_2_2_i2v_fast_low_entry,
    wan_2_2_i2v_fast_high_entry,
    qwen_image_fp8_scaled_entry,
    qwen_image_fp8_lightning_4steps_entry,
    # Z Image Turbo entries
    z_image_turbo_bf16_entry,
    z_image_turbo_fp8_scaled_entry,
    qwen_3_4b_text_encoder_entry,
    z_image_turbo_controlnet_union_entry,
)

# Use the models_structure from model_catalog_data
MODEL_CATALOG = models_structure

__all__ = [
    "HIDREAM_INFO_LINK",
    "GGUF_QUALITY_INFO",
    "MODEL_CATALOG",
    "models_structure",
    "ltx_vae_companion_entry",
    "wan_causvid_14b_lora_v2_entry",
    "wan_causvid_14b_lora_entry",
    "wan_causvid_1_3b_lora_entry",
    "wan_self_forcing_lora_entry",
    "wan_lightx2v_lora_entry",
    "wan_uni3c_controlnet_lora_entry",
    "wan_vae_entry",
    "wan_fusionx_i2v_gguf_q4_entry",
    "wan_fusionx_i2v_gguf_q5_entry",
    "wan_fusionx_i2v_gguf_q6_entry",
    "wan_fusionx_i2v_gguf_q8_entry",
    "wan_fusionx_t2v_gguf_q4_entry",
    "wan_fusionx_t2v_gguf_q5_entry",
    "wan_fusionx_t2v_gguf_q6_entry",
    "wan_fusionx_t2v_gguf_q8_entry",
    "wan_2_2_i2v_fast_low_entry",
    "wan_2_2_i2v_fast_high_entry",
    "qwen_image_fp8_scaled_entry",
    "qwen_image_fp8_lightning_4steps_entry",
    # Z Image Turbo entries
    "z_image_turbo_bf16_entry",
    "z_image_turbo_fp8_scaled_entry",
    "qwen_3_4b_text_encoder_entry",
    "z_image_turbo_controlnet_union_entry",
] 